from __future__ import annotations

from typing import Any, Literal, Mapping, Sequence

import numpy as np
from numpy.typing import NDArray

Float32Array = NDArray[np.float32]
BoolArray = NDArray[np.bool_]
UInt64Array = NDArray[np.uint64]
GraphPreset = Literal["low_latency", "balanced", "broad"]
MemoryRecordInput = Mapping[str, Any]
MemoryHit = dict[str, Any]
GraphExplainReport = dict[str, Any]
GraphCacheStats = dict[str, Any]
GraphCacheBudget = dict[str, int]
MemoryEdge = dict[str, Any]

__version__: str

class TurboQuantIndex:
    def __init__(self, dim: int | None = None, bit_width: int = 4) -> None: ...
    def add(self, vectors: Float32Array) -> None: ...
    def search(
        self,
        queries: Float32Array,
        k: int,
        *,
        mask: BoolArray | None = None,
    ) -> tuple[Float32Array, NDArray[np.int64]]: ...
    def write(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> TurboQuantIndex: ...
    def prepare(self) -> None: ...
    def swap_remove(self, idx: int) -> int: ...
    @property
    def dim(self) -> int | None: ...
    @property
    def bit_width(self) -> int: ...
    def __len__(self) -> int: ...

class IdMapIndex:
    def __init__(self, dim: int | None = None, bit_width: int = 4) -> None: ...
    def add_with_ids(self, vectors: Float32Array, ids: UInt64Array) -> None: ...
    def remove(self, id: int) -> bool: ...
    def search(
        self,
        queries: Float32Array,
        k: int,
        *,
        allowlist: UInt64Array | None = None,
    ) -> tuple[Float32Array, UInt64Array]: ...
    def contains(self, id: int) -> bool: ...
    def prepare(self) -> None: ...
    def write(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> IdMapIndex: ...
    @property
    def dim(self) -> int | None: ...
    @property
    def bit_width(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, id: int) -> bool: ...

class GraphMemoryIndex:
    def __init__(self, dim: int, bit_width: int = 4) -> None: ...
    def add_records(
        self,
        vectors: Float32Array,
        records: Sequence[MemoryRecordInput],
    ) -> None: ...
    def add_node(
        self,
        id: int,
        title: str,
        vector: Float32Array,
        tags: Sequence[str],
        *,
        source: str | None = None,
        timestamp_ms: int | None = None,
    ) -> None: ...
    def link_directed(self, from_id: int, to_id: int, weight: float) -> None: ...
    def link_bidirectional(self, a: int, b: int, weight: float) -> None: ...
    def remove_node(self, id: int) -> bool: ...
    def search(
        self,
        query: Float32Array,
        k: int,
        seeds: Sequence[int],
        *,
        max_hops: int = 2,
        required_tags: Sequence[str] | None = None,
        allowed_sources: Sequence[str] | None = None,
        start_ms: int | None = None,
        end_ms: int | None = None,
        candidate_ids: Sequence[int] | None = None,
    ) -> list[MemoryHit]: ...
    def search_batch(
        self,
        queries: Float32Array,
        k: int,
        seeds: Sequence[int],
        *,
        max_hops: int = 2,
        required_tags: Sequence[str] | None = None,
        allowed_sources: Sequence[str] | None = None,
        start_ms: int | None = None,
        end_ms: int | None = None,
        candidate_ids: Sequence[int] | None = None,
    ) -> list[list[MemoryHit]]: ...
    def explain(
        self,
        query: Float32Array,
        k: int,
        seeds: Sequence[int],
        *,
        preset: GraphPreset = "balanced",
        required_tags: Sequence[str] | None = None,
        allowed_sources: Sequence[str] | None = None,
        start_ms: int | None = None,
        end_ms: int | None = None,
        candidate_ids: Sequence[int] | None = None,
    ) -> GraphExplainReport: ...
    def cache_stats(self) -> GraphCacheStats: ...
    def cache_budget_for_preset(self, preset: GraphPreset) -> GraphCacheBudget: ...
    def clear_query_caches(self) -> None: ...
    def clear_metadata_caches(self) -> None: ...
    def clear_all_caches(self) -> None: ...
    def trim_query_caches(self, max_entries_per_cache: int) -> None: ...
    def trim_metadata_caches(self, max_entries_per_cache: int) -> None: ...
    def trim_all_caches(self, max_entries_per_cache: int) -> None: ...
    def trim_caches_for_preset(self, preset: GraphPreset) -> GraphCacheBudget: ...
    def prepare(self) -> None: ...
    def write(self, index_path: str, graph_path: str) -> None: ...
    @classmethod
    def load(cls, index_path: str, graph_path: str) -> GraphMemoryIndex: ...
    def contains(self, id: int) -> bool: ...
    def slot_of(self, id: int) -> int | None: ...
    def record(self, id: int) -> MemoryHit | None: ...
    def neighbors(self, id: int) -> list[MemoryEdge]: ...
    @property
    def dim(self) -> int: ...
    @property
    def bit_width(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, id: int) -> bool: ...
